name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Instalar dependências e rodar testes
      - name: Install dependencies and test
        run: |
          npm install
          npm run test

  dockerize-backend:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Construir a imagem Docker para o backend
      - name: Build Docker image for NestJS
        run: |
          docker build -t my-backend ./nestjs

      # Login no DockerHub (caso precise)
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Push da imagem Docker
      - name: Push Docker image to DockerHub
        run: |
          docker tag my-backend ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

  