name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Rodar testes (não impede o fluxo se falharem)
      - name: Run tests (continue on failure)
        run: |
          npm run test || true

  dockerize-backend:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Construir a imagem Docker para o backend
      - name: Build Docker image for NestJS
        run: |
          docker build --pull --rm -f "./Dockerfile" -t ecommerce-back:latest .

        # Login no DockerHub
      - name: Docker login
        uses: docker/login-action@v1
        with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password:  ${{ secrets.DOCKER_PASSWORD }}
      
      # Passo 4: Tag e Push da imagem Docker para o DockerHub
      - name: Tag and Push Docker image to DockerHub
        run: |
          docker tag ecommerce-back:latest nunesjefferson425/ecommerce-back:latest
          docker push nunesjefferson425/ecommerce-back:latest