

POST http://localhost:3000/product/create 
Content-Type: application/json

{
   "name":"Tenis Nike Air Max",

    "description":"Tenis criado para homenagear grande astro do NBA",

   "price" : 29,

   "discount": 10,

   "orderItems":[]
}